before_install:
  - sudo cp -f install/openssl.cnf /etc/ssl/openssl.cnf
  - test -x ~/ruby-2.1.2-gost/bin/ruby || (cat install/enable_gost.patch | env CONFIGURE_OPTS="--disable-install-rdoc" ruby-build --patch 2.1.2 ~/ruby-2.1.2-gost)
  - export GEM_HOME=~/rubygems
  - export PATH=~/ruby-2.1.2-gost/bin:~/rubygems/bin:$PATH
  - locate libgost.so
  - openssl version
  - gem install bundler --no-ri --no-rdoc
  - ruby --version
  - gem --version
  - bundle --version

install: 
  - bundle install

cache:
  directories:
    - ~/ruby-2.1.2-gost
    - ~/rubygems

script:
  - bundle exec rake test
