image: vexor-trusty-full

before_install:
  - sudo bash -l -c "cat $(pwd)/install/openssl.cnf.tail | cat - /etc/ssl/openssl.cnf > /tmp/out && mv /tmp/out /etc/ssl/openssl.cnf"
  - sudo bash -l -c 'cat install/openssl.cnf.tail >> /etc/ssl/openssl.cnf'
  - openssl ciphers |  tr ":" "\n" | grep GOST
  - test -x ~/ruby-2.1.2-gost/bin/ruby || (cat install/enable_gost.patch | env CONFIGURE_OPTS="--disable-install-rdoc" ruby-build --patch 2.1.2 ~/ruby-2.1.2-gost)
  - export GEM_HOME=~/rubygems
  - export PATH=~/ruby-2.1.2-gost/bin:~/rubygems/bin:$PATH
  - gem install bundler --no-ri --no-rdoc
  - ruby --version
  - gem --version
  - bundle --version

install: 
  - bundle install

cache:
  directories:
    - ~/ruby-2.1.2-gost
    - ~/rubygems

script:
  - bundle exec rake test
